# Generated by Django 6.0.1 on 2026-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COMERCIAL', 'Comercial'), ('LECTURA', 'Lectura')], max_length=100),
        ),
    ]
