# Generated by Django 6.0.1 on 2026-04-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estadocliente',
            unique_together={('empresa', 'nombre')},
        ),
    ]
