# Generated by Django 6.0.1 on 2026-04-28 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_estadocliente_unique_together'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente_creado', 'Cliente creado'), ('cliente_actualizado', 'Cliente actualizado'), ('estado_cambiado', 'Estado cambiado'), ('cliente_eliminado', 'Cliente eliminado'), ('cliente_restaurado', 'Cliente restaurado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_actividades', to='clients.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actividad_cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
