# Generated by Django 6.0.1 on 2026-03-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campanaemail')),
            ],
        ),
        migrations.AddField(
            model_name='campanaemail',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.plantillaemail'),
        ),
    ]
