# Generated by Django 6.0.1 on 2026-03-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsend',
            name='email_destino',
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.cliente'),
        ),
    ]
