# Generated by Django 6.0.1 on 2026-03-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaignsend_email_destino_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanaemail',
            name='empresa',
            field=models.ForeignKey(default='62a5fb08-f51d-4652-a30a-16e7c4818f0c', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.empresa'),
            preserve_default=False,
        ),
    ]
