# Generated by Django 6.0.1 on 2026-04-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignsend_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsend',
            name='error_mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
