# Generated by Django 6.0.1 on 2026-04-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaignsend_error_mensaje'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaemail',
            name='empresa',
            field=models.ForeignKey(default='62a5fb08-f51d-4652-a30a-16e7c4818f0c', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignsend',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
